# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'api/MovieBot.sln'
    arguments: '-c Release -r linux-x64'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'api/MovieBot.Worker/bin/Release/netcoreapp3.0/linux-x64'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/worker'
    CleanTargetFolder: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'api/MovieBot.Api/bin/Release/netcoreapp3.0/linux-x64'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/api'
    CleanTargetFolder: true

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- task: Yarn@3
  inputs:
    projectDirectory: 'ui'
    arguments: 'install --check-files'

- task: Yarn@3
  inputs:
    projectDirectory: 'ui'
    arguments: 'build'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'ui/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ui'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'